Checkpoints - Around 60
raduschirliu/cpsc585 pull request #114
Opened 2023-03-17 22:53 UTC by suvratkumra

Importing using a custom file which has all the vertices. 
Manually rotating them to align with the map.

2023-03-18 19:02 UTC, raduschirliu requested changes

2023-03-18 19:02 UTC, raduschirliu commented on game/src/engine/scene/Entity.cpp
> +
Should be const after they're created, don't want to have a setter

2023-03-18 20:36 UTC, suvratkumra commented on game/src/game/Checkpoints.h
> +};
I have no idea why i inherited from GameApp, im not even using anything it provides lol

2023-03-20 04:26 UTC, raduschirliu approved these changes
Looks good!

2023-03-20 14:18 UTC, merged